config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  root 'home#top'
  get 'home/about'
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get 'search/search'

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    #binding.pry
    book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = book.id
    if @book_comment.save
    redirect_to book_path(book), notice: "successfully created comment!"
    else
      @new_book = Book.new
      @book = Book.find(params[:book_id])
      @user = User.find_by(id: current_user.id)
      render 'books/show'
    end

  end

  def destroy
    book = Book.find(params[:book_id])
    book_comment = BookComment.find(params[:id])
    #comment = current_user.book_comments
    book_comment.destroy
    redirect_to book_path(book), notice: "successfully deleated comment!"
  end

private
def book_comment_params
    params.require(:book_comment).permit(:comment)
end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
<% @book.book_comments.each do |book_comment| %>
  <li class="comment">
      <span><%= book_comment.comment %></span><br>
      <span><%= book_comment.user.name %></span>
      <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
      <span><%if book_comment.user == current_user %>
      <%= link_to "Destroy",book_book_comment_path(book_comment.book, book_comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger pull-right" %></span>
      <% end %>
  </li>
<% end %>

app/views/book_comments/_form.html.erb
<%= form_for [book, book_comment] do |f| %>

  <% if @book_comment.errors.any? %>
    <h3><%= @book_comment.errors.count %>error occurrence</h3><!--エラーメッセ-->
    <ul>
      <% @book_comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

    <div class="form-group">
      <div class="form-group">
          <%= f.text_area :comment, class: 'form-control', rows: 4, placeholder: "コメントをここに" %>
      </div>
    </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
<% end %>